import Link from 'next/link'
import { TrendingUp, ArrowLeft } from 'lucide-react'

export const metadata = {
  title: 'Terms of Service — ARIA Research',
  description: 'Terms of Service for ARIA Research — AI-powered investment research platform.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50">
      <header className="border-b border-gray-200 bg-white">
        <div className="mx-auto max-w-3xl px-4 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-600">
              <TrendingUp className="h-5 w-5 text-white" />
            </div>
            <span className="font-bold text-gray-900">ARIA Research</span>
          </Link>
          <Link href="/dashboard" className="flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-900">
            <ArrowLeft className="h-4 w-4" /> Back to dashboard
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-4 py-12 space-y-8">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
          <p className="text-gray-500">Last updated: May 2026</p>
        </div>

        {[
          {
            title: '1. About ARIA Research',
            content: `ARIA Research is an AI-powered investment research platform that analyses publicly available market data and generates research insights for informational purposes.

ARIA Research is NOT registered with SEBI as a Research Analyst (RA) under SEBI (Research Analysts) Regulations, 2014, or as an Investment Adviser (IA) under SEBI (Investment Advisers) Regulations, 2013. The platform is a research and information tool only.

By using ARIA Research, you acknowledge that you understand this distinction and agree to these Terms of Service.`,
          },
          {
            title: '2. Use of Research Content',
            content: `All research, analysis, insights, stock screening results, SIP projections, and other content generated by ARIA Research ("Research Content") is:

• AI-generated using publicly available market data and proprietary analysis models
• For educational and informational purposes only
• Not to be construed as investment advice, a recommendation to buy or sell any security, or a solicitation of any kind
• Not personalised investment advice under Indian securities law

You, the user, are solely responsible for all investment decisions you make. ARIA Research does not make investment decisions on your behalf and is not liable for any decisions you make based on Research Content.`,
          },
          {
            title: '3. No Liability for Investment Outcomes',
            content: `ARIA Research, its developers, operators, and contributors expressly disclaim all liability for:

• Any investment losses arising directly or indirectly from use of this platform
• Any investment decisions made on the basis of AI-generated research content
• Inaccuracies, delays, or errors in third-party market data (sourced from Yahoo Finance and other providers)
• Service interruptions, technical errors, or AI model limitations

Securities markets are inherently unpredictable. Past performance shown on this platform is not indicative of future results. No projection, estimate, or target price shown on ARIA Research constitutes a guarantee of any outcome.`,
          },
          {
            title: '4. Data and Privacy',
            content: `ARIA Research collects and processes the following data to provide its services:

• Account information: name, email address
• Investment profile: risk tolerance, goals, income bracket, experience level (entered during onboarding)
• Usage data: research runs, watchlist activity, portfolio holdings (entered manually by you)

This data is:
• Stored in an encrypted database hosted on secure cloud infrastructure
• Used only to personalise your research experience and deliver the service
• Never sold to third parties
• Subject to our Privacy Policy at /privacy

ARIA Research does not access your brokerage accounts, bank accounts, or any external financial accounts. All portfolio data is entered manually by you.`,
          },
          {
            title: '5. Subscription Terms',
            content: `Research Starter (Free): The free tier is available indefinitely at no cost. Features are subject to daily usage limits as described on the pricing page.

Research Pro (₹299/month or ₹2,499/year): The Pro subscription gives you access to unlimited research runs, advanced SIP analysis, price alerts, and the weekly MERCURY digest. Payment is processed securely by Razorpay. Prices shown include 18% GST.

Refund Policy: If you upgrade to Pro and are not satisfied, you may request a full refund within 7 days of your first payment by contacting us. No refunds are issued after 7 days.

Cancellation: You may cancel your Pro subscription at any time. Cancellation stops future renewals. You retain Pro access until the end of your current billing period.

ARIA Research reserves the right to change subscription pricing with 30 days' advance notice.`,
          },
          {
            title: '6. Governing Law',
            content: `These Terms of Service are governed by the laws of India. Any disputes arising from these terms or your use of ARIA Research shall be subject to the exclusive jurisdiction of the courts of India.

If you have questions about these Terms, contact us at the email address listed in your account settings.`,
          },
        ].map(({ title, content }) => (
          <section key={title} className="bg-white rounded-xl border border-gray-200 p-6">
            <h2 className="text-lg font-semibold text-gray-900 mb-3">{title}</h2>
            <div className="text-gray-700 text-sm leading-relaxed whitespace-pre-line">{content}</div>
          </section>
        ))}

        <p className="text-xs text-gray-400 text-center">
          <Link href="/disclaimer" className="underline">Disclaimer</Link> · <Link href="/privacy" className="underline">Privacy Policy</Link>
        </p>
      </main>
    </div>
  )
}
