'use client'

import { useState } from 'react'
import { AlertTriangle, X, Info } from 'lucide-react'

interface DisclaimerProps {
  variant?: 'inline' | 'banner' | 'footer' | 'modal'
}

function DisclaimerModal({ onClose }: { onClose: () => void }) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50">
      <div className="bg-white rounded-2xl shadow-2xl max-w-xl w-full max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between p-6 border-b">
          <h2 className="text-lg font-bold text-gray-900">
            What ARIA Research is — and what it is not
          </h2>
          <button
            onClick={onClose}
            className="p-1.5 text-gray-400 hover:text-gray-700 rounded-lg transition-colors"
          >
            <X className="h-5 w-5" />
          </button>
        </div>
        <div className="p-6 space-y-6 text-sm text-gray-700 leading-relaxed">
          <section>
            <h3 className="font-semibold text-gray-900 mb-2">What we are</h3>
            <p>
              ARIA Research is an AI-powered platform that analyses publicly available market data and
              generates research insights to help you make more informed investment decisions. Think of
              us as a smart research assistant — like having access to institutional-grade data analysis
              tools without the institutional price tag.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-gray-900 mb-2">What we are not</h3>
            <p>
              We are not a SEBI-registered Research Analyst or Investment Adviser. This means our
              research outputs are not legally classified as investment advice under Indian securities
              law. We do not manage your money, execute trades on your behalf, or take responsibility
              for investment outcomes.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-gray-900 mb-2">How to use ARIA Research safely</h3>
            <p>
              Use our research as one input among many. Cross-check with other sources. Understand
              the risks before investing. Never invest more than you can afford to lose. For
              personalised advice tailored to your full financial situation, always consult a
              SEBI-registered adviser.
            </p>
          </section>

          <section>
            <h3 className="font-semibold text-gray-900 mb-2">How to verify a SEBI-registered adviser</h3>
            <p>
              Visit sebi.gov.in → Intermediaries → Registered Entities → Search under Research Analyst
              or Investment Adviser. Any legitimate adviser will display their SEBI registration number
              prominently.
            </p>
          </section>
        </div>
        <div className="p-6 border-t">
          <button
            onClick={onClose}
            className="w-full py-2.5 px-4 bg-gray-900 text-white rounded-lg font-medium hover:bg-gray-700 transition-colors"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  )
}

export function Disclaimer({ variant = 'inline' }: DisclaimerProps) {
  const [showModal, setShowModal] = useState(false)

  if (variant === 'inline') {
    return (
      <p className="text-[11px] text-gray-400 leading-relaxed">
        This research output is generated by AI for informational purposes only. It does not
        constitute investment advice, a solicitation, or a recommendation to buy or sell any
        security. ARIA Research is not registered with SEBI as a Research Analyst or Investment
        Adviser. Always conduct your own due diligence and consult a SEBI-registered financial
        adviser before making any investment decision.
      </p>
    )
  }

  if (variant === 'banner') {
    return (
      <>
        <div className="flex items-center gap-2 rounded-lg border border-amber-200 bg-amber-50 px-4 py-2.5 text-sm text-amber-800">
          <AlertTriangle className="h-4 w-4 shrink-0 text-amber-500" />
          <span>
            <strong>ARIA Research</strong> is an AI research tool, not a SEBI-registered adviser.
            Research outputs are for educational and informational purposes only.{' '}
          </span>
          <button
            onClick={() => setShowModal(true)}
            className="shrink-0 underline font-medium hover:text-amber-900 transition-colors"
          >
            Learn more
          </button>
        </div>
        {showModal && <DisclaimerModal onClose={() => setShowModal(false)} />}
      </>
    )
  }

  if (variant === 'footer') {
    return (
      <>
        <p className="text-xs text-gray-500 leading-relaxed">
          ARIA Research is an independent AI-powered investment research platform. We are not
          registered with SEBI as a Research Analyst (RA) or Investment Adviser (IA). All research,
          analysis, and content published on this platform is for educational and informational
          purposes only and does not constitute investment advice or a solicitation to buy or sell
          securities. Investments in securities markets are subject to market risks. Past performance
          is not indicative of future results. Users are advised to read all related documents
          carefully and consult a SEBI-registered financial adviser before investing.
          © 2025 ARIA Research. All rights reserved.
        </p>
        <button
          onClick={() => setShowModal(true)}
          className="inline-flex items-center gap-1.5 mt-3 text-xs text-gray-400 border border-gray-300 rounded-full px-3 py-1 hover:bg-gray-50 transition-colors"
        >
          <Info className="h-3 w-3" />
          Not SEBI-registered advisory — research tool only
        </button>
        {showModal && <DisclaimerModal onClose={() => setShowModal(false)} />}
      </>
    )
  }

  // variant === 'modal' — render inline trigger or always-open
  return (
    <>
      <button
        onClick={() => setShowModal(true)}
        className="inline-flex items-center gap-1.5 text-xs text-blue-600 hover:underline"
      >
        <Info className="h-3 w-3" />
        What ARIA Research is — and what it is not
      </button>
      {showModal && <DisclaimerModal onClose={() => setShowModal(false)} />}
    </>
  )
}
